using System.Text.Json;
using Carter;
using HostAgent.Commands;
using HostAgent.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Modules.Auth.Identity;

namespace HostAgent.Runtime.Migrations.Qualification.Endpoints;

public sealed class MigrationTwoServerQualificationEndpoints : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        var group = app
            .MapGroup("/api/operator/migrations/sessions/{migrationId}/two-server-qualification")
            .WithTags("Operator / Migrations / Two-server qualification")
            .RequireAuthorization(MemOperatorPolicies.MigrationIntakeOperate);

        group.MapGet("", StateAsync);
        group.MapPost("/source-evidence", ImportSourceEvidenceAsync);
        group.MapGet("/closure", ClosureStateAsync);
        group.MapPost("/closure", CloseAsync);
        group.MapGet("/closure/report", DownloadClosureReportAsync);
    }

    private static async Task<IResult> StateAsync(
        HttpContext httpContext,
        string migrationId,
        MigrationTwoServerQualificationService service,
        CancellationToken cancellationToken)
    {
        SetNoStore(httpContext);
        return await ExecuteAsync(() => service.GetStateAsync(migrationId, cancellationToken));
    }

    private static async Task<IResult> ImportSourceEvidenceAsync(
        HttpContext httpContext,
        string migrationId,
        [FromBody] MigrationTwoServerSourceEvidenceEnvelope? envelope,
        MigrationTwoServerQualificationService service,
        IAuthorizationService authorizationService,
        CancellationToken cancellationToken)
    {
        SetNoStore(httpContext);
        var stepUp = await HostAgentEndpointOperatorGuard
            .ValidateRecentStepUpForCurrentControlPlaneSessionAsync(
                httpContext,
                authorizationService);
        if (stepUp is not null)
        {
            return stepUp;
        }

        if (envelope is null)
        {
            return Results.BadRequest(new HostAgentErrorResponse(
                "migration_two_server_source_evidence_required",
                "Provide the hash-bound source qualification envelope generated by mem-migrate on the retained MEM 0.1.0 server."));
        }

        return await ExecuteAsync(() => service.ImportAsync(
            migrationId,
            envelope,
            cancellationToken));
    }

    private static async Task<IResult> ClosureStateAsync(
        HttpContext httpContext,
        string migrationId,
        MigrationTwoServerQualificationClosureService service,
        CancellationToken cancellationToken)
    {
        SetNoStore(httpContext);
        return await ExecuteAsync(() => service.GetStateAsync(migrationId, cancellationToken));
    }

    private static async Task<IResult> CloseAsync(
        HttpContext httpContext,
        string migrationId,
        [FromBody] MigrationTwoServerQualificationClosureRequest? request,
        MigrationTwoServerQualificationClosureService service,
        IAuthorizationService authorizationService,
        CancellationToken cancellationToken)
    {
        SetNoStore(httpContext);
        var stepUp = await HostAgentEndpointOperatorGuard
            .ValidateRecentStepUpForCurrentControlPlaneSessionAsync(
                httpContext,
                authorizationService);
        if (stepUp is not null)
        {
            return stepUp;
        }

        if (request is null)
        {
            return Results.BadRequest(new HostAgentErrorResponse(
                "migration_two_server_qualification_closure_request_required",
                "Provide the reviewed production qualification closure acknowledgements."));
        }

        return await ExecuteAsync(() => service.CloseAsync(
            migrationId,
            request,
            cancellationToken));
    }

    private static async Task<IResult> DownloadClosureReportAsync(
        HttpContext httpContext,
        string migrationId,
        MigrationTwoServerQualificationClosureService service,
        IAuthorizationService authorizationService,
        CancellationToken cancellationToken)
    {
        SetNoStore(httpContext);
        var stepUp = await HostAgentEndpointOperatorGuard
            .ValidateRecentStepUpForCurrentControlPlaneSessionAsync(
                httpContext,
                authorizationService);
        if (stepUp is not null)
        {
            return stepUp;
        }

        try
        {
            var report = await service.GetReportAsync(migrationId, cancellationToken);
            var bytes = JsonSerializer.SerializeToUtf8Bytes(
                report,
                new JsonSerializerOptions(JsonSerializerDefaults.Web) { WriteIndented = true });
            return Results.File(
                bytes,
                "application/json",
                $"{report.Payload.ClosureId}.mem-production-qualification-closure.json");
        }
        catch (FileNotFoundException ex)
        {
            return Results.NotFound(new HostAgentErrorResponse(
                "migration_two_server_qualification_not_found",
                ex.Message));
        }
        catch (InvalidDataException ex)
        {
            return Results.Json(
                new HostAgentErrorResponse(
                    "migration_two_server_qualification_evidence_invalid",
                    ex.Message),
                statusCode: StatusCodes.Status409Conflict);
        }
        catch (InvalidOperationException ex)
        {
            return Results.Json(
                new HostAgentErrorResponse(
                    "migration_two_server_qualification_closure_blocked",
                    ex.Message),
                statusCode: StatusCodes.Status409Conflict);
        }
    }

    private static async Task<IResult> ExecuteAsync<T>(Func<Task<T>> action)
    {
        try
        {
            return Results.Ok(await action());
        }
        catch (FileNotFoundException ex)
        {
            return Results.NotFound(new HostAgentErrorResponse(
                "migration_two_server_qualification_not_found",
                ex.Message));
        }
        catch (InvalidDataException ex)
        {
            return Results.Json(
                new HostAgentErrorResponse(
                    "migration_two_server_qualification_evidence_invalid",
                    ex.Message),
                statusCode: StatusCodes.Status409Conflict);
        }
        catch (InvalidOperationException ex)
        {
            return Results.Json(
                new HostAgentErrorResponse(
                    "migration_two_server_qualification_blocked",
                    ex.Message),
                statusCode: StatusCodes.Status409Conflict);
        }
    }

    private static void SetNoStore(HttpContext httpContext)
    {
        httpContext.Response.Headers.CacheControl = "no-store";
        httpContext.Response.Headers.Pragma = "no-cache";
    }
}
