<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mem.Migrate.Core/Mem.Migrate.Core.csproj" />
    <ProjectReference Include="../../src/Mem.Migrate.Infrastructure/Mem.Migrate.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Mem.Migrate.Legacy.V010/Mem.Migrate.Legacy.V010.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
