using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using HostAgent.Runtime.Migrations.Assurance;
using Infrastructure.Data.Entities.Migrations;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace HostAgent.Runtime.Migrations.Qualification;

/// <summary>
/// Imports the source-host qualification envelope generated by mem-migrate, independently
/// observes the target host, proves the hosts and Docker Engines are distinct, and binds the
/// result to the accepted normal MEM runtime and its first native baseline backup.
/// </summary>
public sealed class MigrationTwoServerQualificationService(
    MemDbContext db,
    IMigrationTargetHostIdentityProbe targetHostIdentityProbe,
    TimeProvider timeProvider,
    ILogger<MigrationTwoServerQualificationService> logger)
{
    internal const string SourceEvidenceSchemaVersion =
        "mem.migration.two-server-source-evidence.v1";

    private static readonly JsonSerializerOptions JsonOptions =
        new(JsonSerializerDefaults.Web);

    public async Task<MigrationTwoServerQualificationStateResponse> GetStateAsync(
        string migrationId,
        CancellationToken cancellationToken)
    {
        var intake = await LoadAsync(migrationId, tracking: false, cancellationToken);
        var assurance = ResolveAssuranceOrNull(intake);
        if (intake.TwoServerQualification is not null)
        {
            return BuildQualifiedState(intake, intake.TwoServerQualification, assurance: assurance);
        }

        if (assurance is not null && MigrationAssuranceProjection.IsSimplified(assurance))
        {
            return new MigrationTwoServerQualificationStateResponse(
                Source: "control-plane",
                Status: "not-applicable-simplified-assurance",
                MigrationId: migrationId,
                QualificationEligible: false,
                Qualified: false,
                Assurance: assurance,
                Qualification: null,
                Blockers: Array.Empty<string>(),
                Detail: "Two-server source-freeze qualification is not part of simplified assurance. The migration is complete after acceptance and the first native MEM baseline backup; the completion report records that source-freeze evidence, final recapture, and independent post-capture write exclusion were not collected.");
        }

        var blockers = BuildEligibilityBlockers(intake);
        return new MigrationTwoServerQualificationStateResponse(
            Source: "control-plane",
            Status: blockers.Count == 0 ? "ready-for-source-evidence" : "blocked",
            MigrationId: migrationId,
            QualificationEligible: blockers.Count == 0,
            Qualified: false,
            Assurance: assurance,
            Qualification: null,
            Blockers: blockers,
            Detail: blockers.Count == 0
                ? "Import the hash-bound source qualification envelope from the retained MEM 0.1.0 server. MEM will independently prove this target uses a different Linux machine and Docker Engine."
                : "Two-server qualification remains blocked until migration acceptance and the first native MEM baseline backup are complete.");
    }

    public async Task<MigrationTwoServerQualificationStateResponse> ImportAsync(
        string migrationId,
        MigrationTwoServerSourceEvidenceEnvelope envelope,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(envelope);
        ValidateSourceEvidenceEnvelope(envelope);
        ValidateSourceEvidenceProof(envelope.Payload);

        var intake = await LoadAsync(migrationId, tracking: true, cancellationToken);
        var assurance = ResolveAssuranceOrNull(intake);
        if (assurance is not null && MigrationAssuranceProjection.IsSimplified(assurance))
        {
            throw new InvalidOperationException(
                "Two-server source-freeze qualification is not applicable to an operator-attested snapshot migration. Use the accepted-baseline completion report as the simplified release handoff.");
        }

        if (intake.TwoServerQualification is not null)
        {
            if (string.Equals(
                    intake.TwoServerQualification.SourceEvidenceSha256,
                    envelope.PayloadSha256,
                    StringComparison.OrdinalIgnoreCase))
            {
                return BuildQualifiedState(intake, intake.TwoServerQualification);
            }

            throw new InvalidOperationException(
                "Two-server qualification is already closed with different source evidence.");
        }

        var blockers = BuildEligibilityBlockers(intake);
        if (blockers.Count > 0)
        {
            throw new InvalidOperationException(
                $"Two-server qualification is blocked: {string.Join("; ", blockers)}");
        }

        var plan = intake.ProductionAdoption!;
        var acceptance = intake.Acceptance!;
        var baseline = acceptance.BaselineBackupHandoff ?? intake.BaselineBackupHandoff!;
        var source = intake.Sources.Single();
        var revision = plan.PackageRevision;
        var expected = new MigrationTwoServerQualificationExpectedBindings(
            MigrationId: intake.IntakeId,
            SourceMigrationId: revision.ArchiveMigrationId!,
            PackageRevisionId: revision.PackageRevisionId,
            EncryptedPackageSha256: revision.EncryptedPackageSha256!,
            EncryptedPackageBytes: revision.PackageSizeBytes!.Value,
            SourceArchiveSha256: revision.DecryptedArchiveSha256!,
            SourceFingerprint: source.SourceFingerprint,
            MatrixServerName: plan.MatrixServerName);
        ValidateBindings(envelope.Payload, expected);

        var targetHost = await targetHostIdentityProbe.ObserveAsync(cancellationToken);
        ValidateDistinctHostIdentities(envelope.Payload.SourceHost, targetHost);

        var nowUtc = timeProvider.GetUtcNow().UtcDateTime;
        var qualificationId = CreateId("mtq", nowUtc);
        var evidencePayload = new MigrationTwoServerQualificationEvidencePayload(
            QualificationId: qualificationId,
            QualifiedAtUtc: nowUtc,
            MigrationId: intake.IntakeId,
            SourceMigrationId: revision.ArchiveMigrationId!,
            PackageRevisionId: revision.PackageRevisionId,
            EncryptedPackageSha256: revision.EncryptedPackageSha256!,
            SourceEvidenceAttemptId: envelope.Payload.QualificationAttemptId,
            SourceEvidenceSha256: envelope.PayloadSha256.ToLowerInvariant(),
            SourceFingerprint: source.SourceFingerprint,
            SourceStackSlug: envelope.Payload.SourceStackSlug,
            MatrixServerName: envelope.Payload.MatrixServerName,
            FreezeAttemptId: envelope.Payload.FreezeAttemptId,
            FreezePlanId: envelope.Payload.FreezePlanId,
            FreezePlanSha256: envelope.Payload.FreezePlanSha256.ToLowerInvariant(),
            AdoptionPlanId: plan.AdoptionPlanId,
            RuntimeStackId: plan.RuntimeStackId,
            ProductionVerificationId: plan.ProductionVerificationId!,
            AcceptanceId: acceptance.AcceptanceId,
            BaselineBackupHandoffId: baseline.HandoffId,
            BaselineCatalogEntryId: baseline.CatalogEntryId!,
            SourceHost: envelope.Payload.SourceHost,
            TargetHost: targetHost,
            DistinctMachineIdentity: true,
            DistinctDockerEngineIdentity: true,
            DevelopmentExternalControlPlane: false);
        var qualificationEvidenceJson = JsonSerializer.Serialize(evidencePayload, JsonOptions);
        var qualificationEvidenceSha256 = ComputeQualificationPayloadSha256(evidencePayload);
        var sourceEvidenceJson = JsonSerializer.Serialize(envelope, JsonOptions);
        var qualification = new MigrationTwoServerQualificationEntity
        {
            Id = Guid.NewGuid(),
            QualificationId = qualificationId,
            MigrationIntakeEntityId = intake.Id,
            MigrationIntake = intake,
            Status = "qualified",
            ImportedAtUtc = nowUtc,
            QualifiedAtUtc = nowUtc,
            SourceEvidenceAttemptId = envelope.Payload.QualificationAttemptId,
            SourceEvidenceSha256 = envelope.PayloadSha256.ToLowerInvariant(),
            SourceEvidenceJson = sourceEvidenceJson,
            QualificationEvidenceSha256 = qualificationEvidenceSha256,
            QualificationEvidenceJson = qualificationEvidenceJson,
            SourceMigrationId = revision.ArchiveMigrationId!,
            PackageRevisionId = revision.PackageRevisionId,
            EncryptedPackageSha256 = revision.EncryptedPackageSha256!,
            SourceFingerprint = source.SourceFingerprint,
            SourceStackSlug = envelope.Payload.SourceStackSlug,
            MatrixServerName = envelope.Payload.MatrixServerName,
            FreezeAttemptId = envelope.Payload.FreezeAttemptId,
            FreezePlanId = envelope.Payload.FreezePlanId,
            FreezePlanSha256 = envelope.Payload.FreezePlanSha256.ToLowerInvariant(),
            AdoptionPlanId = plan.AdoptionPlanId,
            RuntimeStackId = plan.RuntimeStackId,
            ProductionVerificationId = plan.ProductionVerificationId!,
            AcceptanceId = acceptance.AcceptanceId,
            BaselineBackupHandoffId = baseline.HandoffId,
            BaselineCatalogEntryId = baseline.CatalogEntryId!,
            SourceMachineIdSha256 = envelope.Payload.SourceHost.MachineIdSha256.ToLowerInvariant(),
            SourceDockerEngineIdSha256 = envelope.Payload.SourceHost.DockerEngineIdSha256.ToLowerInvariant(),
            TargetMachineIdSha256 = targetHost.MachineIdSha256.ToLowerInvariant(),
            TargetDockerEngineIdSha256 = targetHost.DockerEngineIdSha256.ToLowerInvariant(),
            DistinctMachineIdentity = true,
            DistinctDockerEngineIdentity = true,
            DevelopmentExternalControlPlane = false,
        };

        intake.TwoServerQualification = qualification;
        db.MigrationTwoServerQualifications.Add(qualification);
        await db.SaveChangesAsync(cancellationToken);
        logger.LogInformation(
            "Two-server migration qualification completed. MigrationId={MigrationId} QualificationId={QualificationId} RuntimeStackId={RuntimeStackId}",
            migrationId,
            qualificationId,
            plan.RuntimeStackId);
        return BuildQualifiedState(intake, qualification, envelope.Payload, targetHost);
    }

    internal static string ComputeSourcePayloadSha256(
        MigrationTwoServerSourceEvidencePayload payload)
    {
        var json = JsonSerializer.Serialize(payload, JsonOptions);
        return Sha256(json);
    }

    internal static string ComputeQualificationPayloadSha256(
        MigrationTwoServerQualificationEvidencePayload payload)
    {
        var json = JsonSerializer.Serialize(payload, JsonOptions);
        return Sha256(json);
    }

    internal static void ValidateSourceEvidenceEnvelope(
        MigrationTwoServerSourceEvidenceEnvelope envelope)
    {
        if (!string.Equals(
                envelope.SchemaVersion,
                SourceEvidenceSchemaVersion,
                StringComparison.Ordinal))
        {
            throw new InvalidDataException(
                $"Unsupported two-server source evidence schema '{envelope.SchemaVersion}'.");
        }

        if (envelope.Payload is null)
        {
            throw new InvalidDataException("Two-server source evidence has no payload.");
        }

        var actual = ComputeSourcePayloadSha256(envelope.Payload);
        if (!IsSha256(envelope.PayloadSha256) ||
            !string.Equals(actual, envelope.PayloadSha256, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException(
                "The two-server source evidence payload hash is missing or invalid.");
        }
    }

    internal static void ValidateSourceEvidenceProof(
        MigrationTwoServerSourceEvidencePayload payload)
    {
        if (string.IsNullOrWhiteSpace(payload.QualificationAttemptId) ||
            string.IsNullOrWhiteSpace(payload.MigrationId) ||
            string.IsNullOrWhiteSpace(payload.IntakeId) ||
            string.IsNullOrWhiteSpace(payload.PackageRevisionId) ||
            string.IsNullOrWhiteSpace(payload.FreezeAttemptId) ||
            string.IsNullOrWhiteSpace(payload.FreezePlanId) ||
            string.IsNullOrWhiteSpace(payload.SourceStackSlug) ||
            string.IsNullOrWhiteSpace(payload.MatrixServerName) ||
            payload.EncryptedPackageBytes <= 0 ||
            !IsSha256(payload.EncryptedPackageSha256) ||
            !IsSha256(payload.SourceArchiveSha256) ||
            !IsSha256(payload.FreezePlanSha256) ||
            !IsSha256(payload.SourceFingerprint))
        {
            throw new InvalidDataException(
                "Two-server source evidence identity, package, or freeze authority is incomplete.");
        }

        if (!payload.SourceFrozen ||
            payload.PublicRoutingMutationOccurred ||
            payload.DevelopmentExternalControlPlane)
        {
            throw new InvalidDataException(
                "Source evidence must prove a frozen production source with no source-side public routing mutation and no development external control plane.");
        }

        ValidateHostIdentity(payload.SourceHost, "source");
        if (payload.Containers is null || payload.Containers.Count == 0)
        {
            throw new InvalidDataException(
                "Two-server source evidence contains no source container evidence.");
        }

        var writerCount = 0;
        var identities = new HashSet<string>(StringComparer.Ordinal);
        foreach (var container in payload.Containers)
        {
            if (string.IsNullOrWhiteSpace(container.Role) ||
                string.IsNullOrWhiteSpace(container.ContainerId) ||
                string.IsNullOrWhiteSpace(container.ContainerName) ||
                string.IsNullOrWhiteSpace(container.ImageId) ||
                !identities.Add(container.ContainerId) ||
                !container.IdentityMatched)
            {
                throw new InvalidDataException(
                    "Two-server source container evidence is incomplete, duplicated, or identity-mismatched.");
            }

            if (!container.WriterContainer)
            {
                continue;
            }

            writerCount++;
            if (!container.FrozenStatePreserved ||
                container.CurrentlyRunning ||
                !string.Equals(
                    container.CurrentRestartPolicy,
                    "no",
                    StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidDataException(
                    $"Source writer container '{container.ContainerName}' is not still frozen and restart-disabled.");
            }
        }

        if (writerCount == 0)
        {
            throw new InvalidDataException(
                "Two-server source evidence contains no frozen source writer containers.");
        }
    }

    internal static void ValidateBindings(
        MigrationTwoServerSourceEvidencePayload payload,
        MigrationTwoServerQualificationExpectedBindings expected)
    {
        var mismatches = new List<string>();
        AddMismatch(mismatches, "intake", payload.IntakeId, expected.MigrationId);
        AddMismatch(mismatches, "source migration", payload.MigrationId, expected.SourceMigrationId);
        AddMismatch(mismatches, "package revision", payload.PackageRevisionId, expected.PackageRevisionId);
        AddMismatch(mismatches, "encrypted package hash", payload.EncryptedPackageSha256, expected.EncryptedPackageSha256, ignoreCase: true);
        if (payload.EncryptedPackageBytes != expected.EncryptedPackageBytes)
        {
            mismatches.Add("encrypted package size");
        }
        AddMismatch(mismatches, "source archive hash", payload.SourceArchiveSha256, expected.SourceArchiveSha256, ignoreCase: true);
        AddMismatch(mismatches, "source fingerprint", payload.SourceFingerprint, expected.SourceFingerprint, ignoreCase: true);
        AddMismatch(mismatches, "Matrix server name", payload.MatrixServerName, expected.MatrixServerName, ignoreCase: true);

        if (mismatches.Count > 0)
        {
            throw new InvalidDataException(
                $"Two-server source evidence does not bind to the accepted migration: {string.Join(", ", mismatches)}.");
        }
    }

    internal static void ValidateDistinctHostIdentities(
        MigrationTwoServerHostIdentity source,
        MigrationTwoServerHostIdentity target)
    {
        ValidateHostIdentity(source, "source");
        ValidateHostIdentity(target, "target");
        if (string.Equals(
                source.MachineIdSha256,
                target.MachineIdSha256,
                StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException(
                "Two-server qualification failed because the source and target Linux machine identities are the same.");
        }

        if (string.Equals(
                source.DockerEngineIdSha256,
                target.DockerEngineIdSha256,
                StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException(
                "Two-server qualification failed because the source and target Docker Engine identities are the same.");
        }
    }

    internal static MigrationAssuranceSummary? ResolveAssuranceOrNull(
        MigrationIntakeEntity intake)
    {
        if (intake.ProductionAdoption is null)
        {
            return null;
        }

        return MigrationAssuranceProjection.Resolve(intake, intake.ProductionAdoption);
    }

    internal static IReadOnlyList<string> BuildEligibilityBlockers(
        MigrationIntakeEntity intake)
    {
        var blockers = new List<string>();
        var plan = intake.ProductionAdoption;
        var acceptance = intake.Acceptance;
        var baseline = acceptance?.BaselineBackupHandoff ?? intake.BaselineBackupHandoff;

        if (plan is null)
        {
            blockers.Add("A completed normal-runtime production adoption is required.");
        }
        else
        {
            if (!string.Equals(
                    plan.Status,
                    "accepted-baseline-backup-created",
                    StringComparison.OrdinalIgnoreCase))
            {
                blockers.Add("The accepted migrated Runtime Stack must complete its first native baseline backup before two-server qualification.");
            }
            if (!string.Equals(
                    plan.ProductionVerificationStatus,
                    "passed",
                    StringComparison.OrdinalIgnoreCase) ||
                string.IsNullOrWhiteSpace(plan.ProductionVerificationId) ||
                !IsSha256(plan.ProductionVerificationEvidenceSha256))
            {
                blockers.Add("The production adoption is missing its passed durable production-verification authority.");
            }
            if (plan.PackageRevision is null ||
                !string.Equals(plan.PackageRevision.Purpose, "final", StringComparison.OrdinalIgnoreCase) ||
                !string.Equals(plan.PackageRevision.Status, "package-validated", StringComparison.OrdinalIgnoreCase) ||
                string.IsNullOrWhiteSpace(plan.PackageRevision.ActivePurposeKey) ||
                !string.Equals(plan.PackageRevision.CaptureKind, "final", StringComparison.OrdinalIgnoreCase) ||
                plan.PackageRevision.SourceFrozen != true ||
                plan.PackageRevision.RehearsalOnly != false ||
                string.IsNullOrWhiteSpace(plan.PackageRevision.ArchiveMigrationId) ||
                string.IsNullOrWhiteSpace(plan.PackageRevision.PackageRevisionId) ||
                !IsSha256(plan.PackageRevision.EncryptedPackageSha256) ||
                !IsSha256(plan.PackageRevision.DecryptedArchiveSha256) ||
                plan.PackageRevision.PackageSizeBytes is null or <= 0)
            {
                blockers.Add("The production adoption is not bound to an authoritative final frozen package revision.");
            }
        }

        if (acceptance is null)
        {
            blockers.Add("Migration acceptance must be durable before two-server qualification.");
        }
        else if (!IsSha256(acceptance.PublicVerificationEvidenceSha256) ||
                 plan is null ||
                 !string.Equals(
                     acceptance.PublicVerificationEvidenceSha256,
                     plan.ProductionVerificationEvidenceSha256,
                     StringComparison.OrdinalIgnoreCase))
        {
            blockers.Add("Migration acceptance is missing its exact production-verification evidence binding.");
        }

        if (baseline is null ||
            !string.Equals(baseline.Status, "created", StringComparison.OrdinalIgnoreCase) ||
            string.IsNullOrWhiteSpace(baseline.HandoffId) ||
            string.IsNullOrWhiteSpace(baseline.CatalogEntryId))
        {
            blockers.Add("The first native MEM baseline backup must exist in the Backup Catalog.");
        }

        if (intake.Sources.Count != 1 ||
            !IsSha256(intake.Sources.SingleOrDefault()?.SourceFingerprint))
        {
            blockers.Add("Exactly one validated source fingerprint is required for two-server qualification.");
        }

        return blockers.Distinct(StringComparer.Ordinal).ToArray();
    }

    private async Task<MigrationIntakeEntity> LoadAsync(
        string migrationId,
        bool tracking,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(migrationId))
        {
            throw new FileNotFoundException("Migration Session was not found.");
        }

        IQueryable<MigrationIntakeEntity> query = db.MigrationIntakes
            .Include(x => x.Sources)
            .Include(x => x.ProductionAuthorities)
                .ThenInclude(x => x.PackageRevision)
            .Include(x => x.ProductionAdoption)!
                .ThenInclude(x => x!.PackageRevision)
            .Include(x => x.ProductionAdoption)!
                .ThenInclude(x => x!.CandidateArtifact)
            .Include(x => x.ProductionAdoption)!
                .ThenInclude(x => x!.StagingRun)
            .Include(x => x.Acceptance)!
                .ThenInclude(x => x!.BaselineBackupHandoff)
            .Include(x => x.BaselineBackupHandoff)
            .Include(x => x.TwoServerQualification);
        if (!tracking)
        {
            query = query.AsNoTracking();
        }

        return await query.SingleOrDefaultAsync(
                   item => item.IntakeId == migrationId,
                   cancellationToken)
               ?? throw new FileNotFoundException("Migration Session was not found.");
    }

    private static MigrationTwoServerQualificationStateResponse BuildQualifiedState(
        MigrationIntakeEntity intake,
        MigrationTwoServerQualificationEntity qualification,
        MigrationTwoServerSourceEvidencePayload? sourcePayload = null,
        MigrationTwoServerHostIdentity? targetHost = null,
        MigrationAssuranceSummary? assurance = null)
    {
        if (sourcePayload is null)
        {
            var sourceEnvelope = ReadSourceEnvelope(qualification.SourceEvidenceJson);
            ValidateSourceEvidenceEnvelope(sourceEnvelope);
            if (!string.Equals(
                    sourceEnvelope.PayloadSha256,
                    qualification.SourceEvidenceSha256,
                    StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidDataException("Stored source qualification evidence no longer matches its durable identity.");
            }
            sourcePayload = sourceEnvelope.Payload;
        }

        var qualificationEvidence = ReadQualificationEvidence(qualification.QualificationEvidenceJson);
        if (!string.Equals(
                ComputeQualificationPayloadSha256(qualificationEvidence),
                qualification.QualificationEvidenceSha256,
                StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("Stored two-server qualification evidence failed SHA-256 validation.");
        }
        ValidateStoredQualificationEvidence(qualification, qualificationEvidence);
        targetHost ??= qualificationEvidence.TargetHost;
        var sourceHost = sourcePayload.SourceHost;
        assurance ??= ResolveAssuranceOrNull(intake);
        return new MigrationTwoServerQualificationStateResponse(
            Source: "control-plane",
            Status: qualification.Status,
            MigrationId: intake.IntakeId,
            QualificationEligible: false,
            Qualified: true,
            Assurance: assurance,
            Qualification: new MigrationTwoServerQualificationDto(
                qualification.QualificationId,
                qualification.Status,
                qualification.ImportedAtUtc,
                qualification.QualifiedAtUtc,
                qualification.SourceEvidenceAttemptId,
                qualification.SourceEvidenceSha256,
                qualification.QualificationEvidenceSha256,
                qualification.SourceMigrationId,
                qualification.PackageRevisionId,
                qualification.SourceStackSlug,
                qualification.MatrixServerName,
                qualification.AdoptionPlanId,
                qualification.RuntimeStackId,
                qualification.ProductionVerificationId,
                qualification.AcceptanceId,
                qualification.BaselineBackupHandoffId,
                qualification.BaselineCatalogEntryId,
                sourceHost,
                targetHost,
                qualification.DistinctMachineIdentity,
                qualification.DistinctDockerEngineIdentity,
                sourcePayload.Containers),
            Blockers: Array.Empty<string>(),
            Detail: "The accepted migration is qualified against distinct MEM 0.1.0 source and MEM 0.2.0 target Linux hosts and Docker Engines.");
    }


    internal static void ValidateStoredQualificationEvidence(
        MigrationTwoServerQualificationEntity entity,
        MigrationTwoServerQualificationEvidencePayload payload)
    {
        var mismatches = new List<string>();
        AddMismatch(mismatches, "qualification", payload.QualificationId, entity.QualificationId);
        AddMismatch(mismatches, "migration", payload.MigrationId, entity.MigrationIntake.IntakeId);
        AddMismatch(mismatches, "source migration", payload.SourceMigrationId, entity.SourceMigrationId);
        AddMismatch(mismatches, "package revision", payload.PackageRevisionId, entity.PackageRevisionId);
        AddMismatch(mismatches, "source evidence", payload.SourceEvidenceSha256, entity.SourceEvidenceSha256, ignoreCase: true);
        AddMismatch(mismatches, "source fingerprint", payload.SourceFingerprint, entity.SourceFingerprint, ignoreCase: true);
        AddMismatch(mismatches, "source stack", payload.SourceStackSlug, entity.SourceStackSlug);
        AddMismatch(mismatches, "Matrix server name", payload.MatrixServerName, entity.MatrixServerName, ignoreCase: true);
        AddMismatch(mismatches, "adoption plan", payload.AdoptionPlanId, entity.AdoptionPlanId);
        AddMismatch(mismatches, "production verification", payload.ProductionVerificationId, entity.ProductionVerificationId);
        AddMismatch(mismatches, "acceptance", payload.AcceptanceId, entity.AcceptanceId);
        AddMismatch(mismatches, "baseline handoff", payload.BaselineBackupHandoffId, entity.BaselineBackupHandoffId);
        AddMismatch(mismatches, "baseline catalog entry", payload.BaselineCatalogEntryId, entity.BaselineCatalogEntryId);
        if (payload.RuntimeStackId != entity.RuntimeStackId)
        {
            mismatches.Add("Runtime Stack");
        }
        if (!payload.DistinctMachineIdentity ||
            !payload.DistinctDockerEngineIdentity ||
            payload.DevelopmentExternalControlPlane ||
            !string.Equals(payload.SourceHost.MachineIdSha256, entity.SourceMachineIdSha256, StringComparison.OrdinalIgnoreCase) ||
            !string.Equals(payload.SourceHost.DockerEngineIdSha256, entity.SourceDockerEngineIdSha256, StringComparison.OrdinalIgnoreCase) ||
            !string.Equals(payload.TargetHost.MachineIdSha256, entity.TargetMachineIdSha256, StringComparison.OrdinalIgnoreCase) ||
            !string.Equals(payload.TargetHost.DockerEngineIdSha256, entity.TargetDockerEngineIdSha256, StringComparison.OrdinalIgnoreCase))
        {
            mismatches.Add("host identity proof");
        }

        if (mismatches.Count > 0)
        {
            throw new InvalidDataException(
                $"Stored two-server qualification evidence no longer matches its durable record: {string.Join(", ", mismatches)}.");
        }
    }

    internal static MigrationTwoServerSourceEvidenceEnvelope ReadSourceEnvelope(string json) =>
        JsonSerializer.Deserialize<MigrationTwoServerSourceEvidenceEnvelope>(json, JsonOptions)
        ?? throw new InvalidDataException("Stored two-server source evidence could not be read.");

    internal static MigrationTwoServerQualificationEvidencePayload ReadQualificationEvidence(string json) =>
        JsonSerializer.Deserialize<MigrationTwoServerQualificationEvidencePayload>(json, JsonOptions)
        ?? throw new InvalidDataException("Stored two-server qualification evidence could not be read.");

    private static void ValidateHostIdentity(
        MigrationTwoServerHostIdentity? host,
        string boundary)
    {
        if (host is null ||
            !IsSha256(host.MachineIdSha256) ||
            !IsSha256(host.DockerEngineIdSha256) ||
            string.IsNullOrWhiteSpace(host.MachineName) ||
            string.IsNullOrWhiteSpace(host.OperatingSystem) ||
            string.IsNullOrWhiteSpace(host.Architecture) ||
            string.IsNullOrWhiteSpace(host.DockerName) ||
            string.IsNullOrWhiteSpace(host.DockerServerVersion))
        {
            throw new InvalidDataException(
                $"The {boundary} host identity evidence is incomplete.");
        }
    }

    private static void AddMismatch(
        ICollection<string> mismatches,
        string label,
        string? actual,
        string? expected,
        bool ignoreCase = false)
    {
        if (!string.Equals(
                actual,
                expected,
                ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal))
        {
            mismatches.Add(label);
        }
    }

    private static bool IsSha256(string? value) =>
        value is { Length: 64 } && value.All(Uri.IsHexDigit);

    private static string Sha256(string value) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)))
            .ToLowerInvariant();

    private static string CreateId(string prefix, DateTime utc) =>
        $"{prefix}_{utc:yyyyMMdd-HHmmssZ}_{Guid.NewGuid():N}";
}
