using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Configuration;

namespace HostAgent.Runtime.Backups.Coordination;

/// <summary>
/// Creates and updates the new canonical per-attempt workspace. This is a
/// human-inspectable projection of the SQLite coordination row, never a second
/// authority for active-source ownership.
/// </summary>
public sealed class RestoreAttemptWorkspaceStore
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    private readonly IConfiguration _configuration;

    public RestoreAttemptWorkspaceStore(IConfiguration configuration)
    {
        _configuration = configuration;
    }

    public string GetSessionDirectoryPath(string restoreSessionId)
    {
        var safeRestoreSessionId = RestoreSourceKeyFactory.NormalizePathSegment(
            restoreSessionId,
            "Restore session id is required.");

        // Restore session ids are generated by the coordinator; normalize only
        // validates the segment here. The directory name remains stable because
        // generated ids are already lowercase.
        var root = Path.GetFullPath(Path.Combine(ResolveDataRoot(), "restore-sessions"));
        var path = Path.GetFullPath(Path.Combine(root, safeRestoreSessionId));

        if (!IsDirectChild(root, path))
        {
            throw new InvalidOperationException("Restore workspace resolves outside the configured mem-data root.");
        }

        return path;
    }

    public async Task EnsureWorkspaceAsync(
        RestoreAttemptSnapshot attempt,
        CancellationToken ct)
    {
        var expectedPath = GetSessionDirectoryPath(attempt.RestoreSessionId);
        if (!string.Equals(
                Path.GetFullPath(attempt.SessionDirectoryPath),
                expectedPath,
                StringComparison.Ordinal))
        {
            throw new InvalidOperationException("Restore attempt workspace path does not match the configured mem-data root.");
        }

        Directory.CreateDirectory(expectedPath);
        EnsurePathIsNotReparsePoint(expectedPath);

        foreach (var name in new[] { "operations", "evidence", "logs", "support" })
        {
            var directory = Path.Combine(expectedPath, name);
            Directory.CreateDirectory(directory);
            EnsurePathIsNotReparsePoint(directory);
        }

        var document = new RestoreAttemptWorkspaceDocument(
            SchemaVersion: 2,
            RestoreSessionId: attempt.RestoreSessionId,
            Source: new RestoreAttemptWorkspaceSource(
                attempt.SourceKind,
                attempt.SourceKey,
                attempt.CatalogEntryId,
                attempt.SourceDisplayName,
                attempt.SourceOriginKind,
                attempt.SourceStackSlug,
                attempt.SourceBackupId),
            Status: attempt.Status,
            CurrentStage: attempt.CurrentStage,
            CreatedAtUtc: attempt.CreatedAtUtc,
            UpdatedAtUtc: attempt.UpdatedAtUtc,
            TerminalAtUtc: attempt.TerminalAtUtc,
            LastEventAtUtc: attempt.LastEventAtUtc,
            LastErrorCode: attempt.LastErrorCode,
            LastErrorSummary: attempt.LastErrorSummary,
            WarningCount: attempt.WarningCount,
            ErrorCount: attempt.ErrorCount,
            RuntimeOperationId: attempt.RuntimeOperationId,
            ArtifactPaths: new RestoreAttemptWorkspaceArtifactPaths(
                attempt.SessionDirectoryPath,
                attempt.LogDirectoryPath,
                attempt.SupportReportPath));

        var sessionPath = Path.Combine(expectedPath, "session.json");
        await WriteJsonAtomicallyAsync(sessionPath, document, ct);
    }

    public bool WorkspaceExists(string restoreSessionId)
    {
        var directory = GetSessionDirectoryPath(restoreSessionId);
        return Directory.Exists(directory) &&
               File.Exists(Path.Combine(directory, "session.json"));
    }

    private async Task WriteJsonAtomicallyAsync<T>(string finalPath, T value, CancellationToken ct)
    {
        var directory = Path.GetDirectoryName(finalPath)
            ?? throw new InvalidOperationException("Restore workspace JSON path has no parent directory.");

        Directory.CreateDirectory(directory);
        EnsurePathIsNotReparsePoint(directory);

        var tempPath = Path.Combine(
            directory,
            $".{Path.GetFileName(finalPath)}.{Guid.NewGuid():N}.tmp");

        try
        {
            await using (var stream = new FileStream(
                             tempPath,
                             FileMode.CreateNew,
                             FileAccess.Write,
                             FileShare.None,
                             bufferSize: 16 * 1024,
                             options: FileOptions.Asynchronous | FileOptions.WriteThrough))
            {
                await JsonSerializer.SerializeAsync(stream, value, JsonOptions, ct);
                await stream.FlushAsync(ct);
            }

            File.Move(tempPath, finalPath, overwrite: true);
        }
        finally
        {
            if (File.Exists(tempPath))
            {
                File.Delete(tempPath);
            }
        }
    }

    private string ResolveDataRoot() =>

        global::Modules.Shared.Storage.MemDataRootResolver.Resolve(_configuration);

    private static bool IsDirectChild(string root, string candidate)
    {
        var normalizedRoot = Path.GetFullPath(root)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) +
            Path.DirectorySeparatorChar;
        var normalizedCandidate = Path.GetFullPath(candidate);

        return normalizedCandidate.StartsWith(normalizedRoot, StringComparison.Ordinal) &&
               !string.Equals(normalizedCandidate, normalizedRoot, StringComparison.Ordinal);
    }

    private static void EnsurePathIsNotReparsePoint(string path)
    {
        var info = new DirectoryInfo(path);
        if (info.Exists && info.Attributes.HasFlag(FileAttributes.ReparsePoint))
        {
            throw new InvalidOperationException("Restore workspace cannot use a symbolic link or reparse point.");
        }
    }
}

public sealed record RestoreAttemptWorkspaceDocument(
    int SchemaVersion,
    string RestoreSessionId,
    RestoreAttemptWorkspaceSource Source,
    string Status,
    string CurrentStage,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc,
    DateTimeOffset? TerminalAtUtc,
    DateTimeOffset? LastEventAtUtc,
    string? LastErrorCode,
    string? LastErrorSummary,
    int WarningCount,
    int ErrorCount,
    Guid? RuntimeOperationId,
    RestoreAttemptWorkspaceArtifactPaths ArtifactPaths);

/// <summary>
/// Durable source snapshots for a catalog-bound restore attempt. Validation IDs
/// are intentionally absent: uploaded ZIP validation is ingestion provenance,
/// not restore identity.
/// </summary>
public sealed record RestoreAttemptWorkspaceSource(
    string SourceKind,
    string SourceKey,
    string CatalogEntryId,
    string DisplayName,
    string OriginKind,
    string? SourceStackSlug,
    string? SourceBackupId);

public sealed record RestoreAttemptWorkspaceArtifactPaths(
    string SessionDirectoryPath,
    string? LogDirectoryPath,
    string? SupportReportPath);
