using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;

namespace HostAgent.Runtime.Coturn;

public static class CoturnRuntimePolicy
{
    public const string ServiceKey = "coturn";
    public const string ContainerName = "mem-coturn";
    public const string ComponentLabel = "platform";
    public const string SecurityPolicyVersion = "mem-0.2.0-v2";
    public const string ContainerConfigPath = "/etc/coturn/turnserver.conf";
    public const string ExpectedRestartPolicy = "unless-stopped";
    public const string StartupUser = "0:0";
    public const int TurnPort = 3478;
    public const int RelayMinPort = 49160;
    public const int RelayMaxPort = 49200;
    public const int UserQuota = 12;
    public const int TotalQuota = 1200;

    private static readonly string[] RequiredSecurityLines =
    [
        "use-auth-secret",
        "fingerprint",
        "no-tls",
        "no-dtls",
        "pidfile=/var/tmp/turnserver.pid",
        "no-tcp-relay",
        "no-multicast-peers",
        "proc-user=nobody",
        "proc-group=nogroup",
        $"user-quota={UserQuota}",
        $"total-quota={TotalQuota}"
    ];

    private static readonly string[] DeniedPeerRanges =
    [
        "0.0.0.0-0.255.255.255",
        "10.0.0.0-10.255.255.255",
        "100.64.0.0-100.127.255.255",
        "127.0.0.0-127.255.255.255",
        "169.254.0.0-169.254.255.255",
        "172.16.0.0-172.31.255.255",
        "192.0.0.0-192.0.0.255",
        "192.0.2.0-192.0.2.255",
        "192.88.99.0-192.88.99.255",
        "192.168.0.0-192.168.255.255",
        "198.18.0.0-198.19.255.255",
        "198.51.100.0-198.51.100.255",
        "203.0.113.0-203.0.113.255",
        "240.0.0.0-255.255.255.255",
        "::1",
        "64:ff9b::-64:ff9b::ffff:ffff",
        "::ffff:0.0.0.0-::ffff:255.255.255.255",
        "100::-100::ffff:ffff:ffff:ffff",
        "2001::-2001:1ff:ffff:ffff:ffff:ffff:ffff:ffff",
        "2002::-2002:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
    ];

    public static string? NormalizeExternalIp(string? value)
    {
        var candidate = value?.Trim();
        if (string.IsNullOrWhiteSpace(candidate))
        {
            return null;
        }

        if (candidate.Contains('%') ||
            !IPAddress.TryParse(candidate, out var address) ||
            (address.AddressFamily == AddressFamily.InterNetworkV6 && address.ScopeId != 0))
        {
            throw new InvalidOperationException(
                "Coturn externalIp must be a valid IPv4 or IPv6 address literal.");
        }

        return address.ToString();
    }

    public static string RenderConfiguration(
        string realm,
        string sharedSecret)
    {
        if (string.IsNullOrWhiteSpace(realm))
        {
            throw new InvalidOperationException("Coturn realm is required.");
        }

        if (string.IsNullOrWhiteSpace(sharedSecret))
        {
            throw new InvalidOperationException("Coturn shared secret is required.");
        }

        var lines = new List<string>
        {
            "# Generated by Message Easy Mode. Contains secret material.",
            "# Do not copy this file into reports, logs, or browser responses.",
            "log-file=stdout",
            $"listening-port={TurnPort}",
            $"realm={realm.Trim()}",
            "use-auth-secret",
            $"static-auth-secret={sharedSecret}",
            $"min-port={RelayMinPort}",
            $"max-port={RelayMaxPort}",
            "fingerprint",
            "no-tls",
            "no-dtls",
            "pidfile=/var/tmp/turnserver.pid",
            "no-tcp-relay",
            "no-multicast-peers",
            "proc-user=nobody",
            "proc-group=nogroup",
            $"user-quota={UserQuota}",
            $"total-quota={TotalQuota}"
        };

        foreach (var range in DeniedPeerRanges)
        {
            lines.Add($"denied-peer-ip={range}");
        }

        return string.Join('\n', lines) + "\n";
    }

    public static bool HasRequiredSecurityPolicy(string? configuration)
    {
        if (string.IsNullOrWhiteSpace(configuration))
        {
            return false;
        }

        var lines = configuration
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Where(line => !line.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);

        return RequiredSecurityLines.All(lines.Contains) &&
               DeniedPeerRanges.All(range => lines.Contains($"denied-peer-ip={range}")) &&
               !lines.Contains("lt-cred-mech") &&
               !lines.Contains("no-cli");
    }

    public static IReadOnlyList<string> BuildContainerCommand(string? externalIp)
    {
        var normalizedExternalIp = NormalizeExternalIp(externalIp);
        var command = new List<string>
        {
            "-c",
            ContainerConfigPath,
            "--allowed-peer-ip=$(hostname -i | awk '{print $1}')"
        };

        // MEM replaces the image's default Cmd. Preserve its detector invocation
        // explicitly; an environment flag alone did not add an external address
        // in the approved image. The image entrypoint expands this fixed command
        // substitution on EVERY start, just like the allowed-peer expression.
        // Operator input is an IP literal only, never an executable expression.
        command.Add(normalizedExternalIp is null
            ? "--external-ip=$(detect-external-ip)"
            : $"--external-ip={normalizedExternalIp}");

        return command;
    }

    public static IReadOnlyDictionary<string, string> BuildPortBindings(
        bool publishRelayPorts)
    {
        var ports = new Dictionary<string, string>
        {
            [$"{TurnPort}/tcp"] = TurnPort.ToString(),
            [$"{TurnPort}/udp"] = TurnPort.ToString()
        };

        if (publishRelayPorts)
        {
            for (var port = RelayMinPort; port <= RelayMaxPort; port++)
            {
                ports[$"{port}/udp"] = port.ToString();
            }
        }

        return ports;
    }

    public static IReadOnlyList<string> BuildPublishedPorts(
        bool publishRelayPorts)
    {
        var ports = new List<string>
        {
            $"{TurnPort}/tcp",
            $"{TurnPort}/udp"
        };

        if (publishRelayPorts)
        {
            ports.Add($"{RelayMinPort}-{RelayMaxPort}/udp");
        }

        return ports;
    }

    public static IReadOnlyList<string> BuildRequiredProductionFirewallPorts() =>
    [
        $"{TurnPort}/tcp",
        $"{TurnPort}/udp",
        $"{RelayMinPort}-{RelayMaxPort}/udp"
    ];

    public static IReadOnlyList<string> BuildTurnUris(string publicHost) =>
    [
        $"turn:{publicHost}:{TurnPort}?transport=udp",
        $"turn:{publicHost}:{TurnPort}?transport=tcp"
    ];

    public static string ComputeSha256(string value)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(value));
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }

    public static bool IsOwned(IEnumerable<KeyValuePair<string, string>>? labels)
    {
        if (labels is null)
        {
            return false;
        }

        string? component = null;
        string? service = null;

        foreach (var label in labels)
        {
            if (string.Equals(label.Key, "mem.component", StringComparison.Ordinal))
            {
                component = label.Value;
            }
            else if (string.Equals(label.Key, "mem.service", StringComparison.Ordinal))
            {
                service = label.Value;
            }
        }

        return string.Equals(component, ComponentLabel, StringComparison.Ordinal) &&
               string.Equals(service, ServiceKey, StringComparison.Ordinal);
    }

    public static CoturnReadinessEvaluation Evaluate(
        CoturnRuntimeObservation observation)
    {
        if (!observation.ContainerExists)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "not-deployed",
                Readiness: "not-deployed",
                Status: "not_ready",
                OperatorStatus: CoturnOperatorStatuses.NotDeployed,
                Ready: false,
                RuntimeExact: false);
        }

        if (!observation.OwnershipVerified)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "collision",
                Readiness: "unavailable",
                Status: "not_ready",
                OperatorStatus: CoturnOperatorStatuses.Conflict,
                Ready: false,
                RuntimeExact: false);
        }

        if (!observation.Running)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "stopped",
                Readiness: "stopped",
                Status: "not_ready",
                OperatorStatus: CoturnOperatorStatuses.Stopped,
                Ready: false,
                RuntimeExact: false);
        }

        if (!observation.DockerInspectionAvailable)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "unknown",
                Status: "inspection_unavailable",
                OperatorStatus: CoturnOperatorStatuses.Unknown,
                Ready: false,
                RuntimeExact: false);
        }

        if (!observation.RuntimeStateHealthy)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "degraded",
                Status: "runtime_degraded",
                OperatorStatus: CoturnOperatorStatuses.NeedsAttention,
                Ready: false,
                RuntimeExact: false);
        }

        if (observation.DomainDriftDetected)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "setup-incomplete",
                Status: "needs_reconfigure",
                OperatorStatus: CoturnOperatorStatuses.RepairRequired,
                Ready: false,
                RuntimeExact: false);
        }

        var runtimeExact =
            observation.RestartPolicyMatches &&
            observation.NetworkAttachmentMatches &&
            observation.NetworkAliasesMatch &&
            observation.ConfigMountMatches &&
            observation.CommandMatches &&
            observation.StartupUserMatches;

        if (!runtimeExact)
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "repair-required",
                Status: "runtime_drift",
                OperatorStatus: CoturnOperatorStatuses.RepairRequired,
                Ready: false,
                RuntimeExact: false);
        }

        if (string.Equals(
                observation.ProtectedEvidenceAccess,
                CoturnProtectedEvidenceAccess.Restricted,
                StringComparison.Ordinal))
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "verification-limited",
                Status: "protected_evidence_restricted",
                OperatorStatus: CoturnOperatorStatuses.VerificationLimited,
                Ready: false,
                RuntimeExact: true);
        }

        if (string.Equals(
                observation.ProtectedEvidenceAccess,
                CoturnProtectedEvidenceAccess.Unavailable,
                StringComparison.Ordinal))
        {
            return new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "unknown",
                Status: "protected_evidence_unavailable",
                OperatorStatus: CoturnOperatorStatuses.Unknown,
                Ready: false,
                RuntimeExact: true);
        }

        var structurallyReady =
            observation.ImageApproved &&
            observation.SecretPresent &&
            observation.ConfigPresent &&
            observation.ConfigHashMatches &&
            observation.SecurityPolicyApplied &&
            observation.RelayPortsPublished;

        return structurallyReady
            ? new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "ready",
                Status: "ok",
                OperatorStatus: CoturnOperatorStatuses.RuntimeReady,
                Ready: true,
                RuntimeExact: true)
            : new CoturnReadinessEvaluation(
                ContainerState: "running",
                Readiness: "setup-incomplete",
                Status: "setup_incomplete",
                OperatorStatus: CoturnOperatorStatuses.RepairRequired,
                Ready: false,
                RuntimeExact: true);
    }

    public static bool CanProvideSynapseConfiguration(
        CoturnReadinessEvaluation evaluation) => evaluation.Ready;
}

public sealed record CoturnRuntimeObservation(
    bool ContainerExists,
    bool Running,
    bool OwnershipVerified,
    bool DockerInspectionAvailable,
    bool RuntimeStateHealthy,
    bool RestartPolicyMatches,
    bool NetworkAttachmentMatches,
    bool NetworkAliasesMatch,
    bool ConfigMountMatches,
    bool CommandMatches,
    bool StartupUserMatches,
    string ProtectedEvidenceAccess,
    bool ImageApproved,
    bool SecretPresent,
    bool ConfigPresent,
    bool ConfigHashMatches,
    bool SecurityPolicyApplied,
    bool RelayPortsPublished,
    bool DomainDriftDetected);

public sealed record CoturnReadinessEvaluation(
    string ContainerState,
    string Readiness,
    string Status,
    string OperatorStatus,
    bool Ready,
    bool RuntimeExact);
