namespace Infrastructure.Data.Entities.Migrations;

/// <summary>
/// Durable proof that an accepted migration was qualified across distinct source and target
/// Linux hosts and Docker Engines. Source evidence remains externally generated by mem-migrate;
/// this entity records only the independently validated target-side import and binding.
/// </summary>
public sealed class MigrationTwoServerQualificationEntity
{
    public Guid Id { get; set; }
    public string QualificationId { get; set; } = default!;
    public Guid MigrationIntakeEntityId { get; set; }
    public MigrationIntakeEntity MigrationIntake { get; set; } = default!;
    public string Status { get; set; } = default!;
    public DateTime ImportedAtUtc { get; set; }
    public DateTime QualifiedAtUtc { get; set; }

    public string SourceEvidenceAttemptId { get; set; } = default!;
    public string SourceEvidenceSha256 { get; set; } = default!;
    public string SourceEvidenceJson { get; set; } = default!;
    public string QualificationEvidenceSha256 { get; set; } = default!;
    public string QualificationEvidenceJson { get; set; } = default!;

    public string SourceMigrationId { get; set; } = default!;
    public string PackageRevisionId { get; set; } = default!;
    public string EncryptedPackageSha256 { get; set; } = default!;
    public string SourceFingerprint { get; set; } = default!;
    public string SourceStackSlug { get; set; } = default!;
    public string MatrixServerName { get; set; } = default!;
    public string FreezeAttemptId { get; set; } = default!;
    public string FreezePlanId { get; set; } = default!;
    public string FreezePlanSha256 { get; set; } = default!;

    public string AdoptionPlanId { get; set; } = default!;
    public Guid RuntimeStackId { get; set; }
    public string ProductionVerificationId { get; set; } = default!;
    public string AcceptanceId { get; set; } = default!;
    public string BaselineBackupHandoffId { get; set; } = default!;
    public string BaselineCatalogEntryId { get; set; } = default!;

    public string SourceMachineIdSha256 { get; set; } = default!;
    public string SourceDockerEngineIdSha256 { get; set; } = default!;
    public string TargetMachineIdSha256 { get; set; } = default!;
    public string TargetDockerEngineIdSha256 { get; set; } = default!;
    public bool DistinctMachineIdentity { get; set; }
    public bool DistinctDockerEngineIdentity { get; set; }
    public bool DevelopmentExternalControlPlane { get; set; }

    public string? ClosureId { get; set; }
    public string? ClosureStatus { get; set; }
    public DateTime? ClosedAtUtc { get; set; }
    public string? ClosureEvidenceSha256 { get; set; }
    public string? ClosureEvidenceJson { get; set; }
    public string? ClosureNote { get; set; }
}
