using HostAgent.Runtime.Backups.AdvancedCutover.Preflight;

namespace HostAgent.Runtime.Backups.AdvancedCutover.Execution;

public sealed record RuntimeStackBackupPublicCutoverExecutionRequest(
    string? Operator,
    string? Note,
    bool ExecuteNpmRouteMutation,
    bool ExecuteCutoverIngressNetworkMutation,
    bool AcknowledgeConfirmationReviewed,
    bool AcknowledgeDockerNetworkMutation,
    bool AcknowledgeNpmMustNotJoinPrivateRestoreNetwork,
    bool AcknowledgeCreatesPublicRoutes,
    bool AcknowledgeNpmRoutesWillChange,
    bool AcknowledgeMatrixFederationExposureMayChange,
    bool AcknowledgeNoDnsMutation,
    bool AcknowledgeNoCertificateMutation,
    bool AcknowledgeNoRuntimePromotion,
    bool AcknowledgeNoAutomaticRollback,
    bool AcknowledgePostCutoverVerificationRequired);

public sealed record RuntimeStackBackupPublicCutoverExecutionResult(
    string Source,
    string Status,
    string ExecutionId,
    string ConfirmationId,
    string PreviewId,
    string ValidationId,
    string CandidateId,
    string? FreshPlanId,
    string RestoreMode,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? FinishedAtUtc,
    string? Operator,
    string? Note,
    bool ExecutionRequested,
    bool ProductionExecutionLocked,
    bool NpmRouteExecutionPerformed,
    bool CutoverIngressNetworkExecutionPerformed,
    bool RuntimePromotionLocked,
    bool DnsMutationLocked,
    bool CertificateMutationLocked,
    RuntimeStackBackupProductionRestoreMutationSummary Mutations,
    RuntimeStackBackupPublicCutoverIngressSummary CutoverIngress,
    RuntimeStackBackupPublicCutoverExecutionCandidateSummary Candidate,
    RuntimeStackBackupPublicCutoverExecutionRouteSummary Routes,
    IReadOnlyList<RuntimeStackBackupPublicCutoverExecutionAcknowledgement> Acknowledgements,
    IReadOnlyList<RuntimeStackBackupPublicCutoverExecutionCheck> Checks,
    IReadOnlyList<string> Blockers,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<string> Errors,
    string? Detail);

public sealed record RuntimeStackBackupPublicCutoverIngressSummary(
    string NetworkName,
    string NpmContainerName,
    string MatrixContainerName,
    string ElementContainerName,
    string? PostgresContainerName,
    string MatrixAlias,
    string ElementAlias,
    string PrivateRestoreNetworkName,
    bool NetworkExistedBefore,
    bool NetworkCreated,
    bool NpmAttachedBefore,
    bool NpmAttachedAfter,
    bool NpmAttachmentChanged,
    bool MatrixAttachedBefore,
    bool MatrixAttachedAfter,
    bool MatrixAttachmentChanged,
    bool MatrixAliasReady,
    bool ElementAttachedBefore,
    bool ElementAttachedAfter,
    bool ElementAttachmentChanged,
    bool ElementAliasReady,
    bool PostgresAttachedToCutoverIngress,
    bool NpmAttachedToPrivateRestoreNetworkBefore,
    bool NpmAttachedToPrivateRestoreNetworkAfter,
    bool DockerNetworksChanged,
    bool Ready,
    string Status,
    IReadOnlyList<string> Notes);

public sealed record RuntimeStackBackupPublicCutoverExecutionCandidateSummary(
    bool CandidateFound,
    string CandidateId,
    string Status,
    string PrivateRuntimeStatus,
    bool PrivateOnly,
    bool Destroyed,
    bool DatabaseImportSucceeded,
    bool SynapseHealthPassed,
    bool ElementHealthPassed,
    string? MatrixServerName,
    string? SynapseContainerName,
    string? ElementContainerName,
    string? Detail);

public sealed record RuntimeStackBackupPublicCutoverExecutionRouteSummary(
    RuntimeStackBackupPublicCutoverExecutionRouteResult Matrix,
    RuntimeStackBackupPublicCutoverExecutionRouteResult Element,
    bool AllRequestedRoutesSucceeded,
    bool AnyRouteMutated,
    IReadOnlyList<string> Notes);

public sealed record RuntimeStackBackupPublicCutoverExecutionRouteResult(
    string Component,
    string? Host,
    string? DesiredForwardHost,
    int? DesiredForwardPort,
    string ForwardScheme,
    int? NpmCertificateId,
    string PreviewAction,
    bool PreviewAvailableForFutureExecution,
    bool FreshRouteCurrentlyExistsBeforeExecution,
    bool FreshRouteAlreadyTargetsCandidateBeforeExecution,
    bool Requested,
    bool Mutated,
    bool Succeeded,
    string ExecutionAction,
    string Status,
    string? NpmProxyHostId,
    bool? SslConfigured,
    bool? Ready,
    string? Warning,
    string? Error,
    string? Detail);

public sealed record RuntimeStackBackupPublicCutoverExecutionAcknowledgement(
    string Code,
    string Label,
    string Description,
    string Severity,
    bool Required,
    bool Acknowledged,
    string Status);

public sealed record RuntimeStackBackupPublicCutoverExecutionCheck(
    string Code,
    string Category,
    string Severity,
    string Status,
    bool Passed,
    string Message,
    string? Detail);

public sealed record RuntimeStackBackupPublicCutoverExecutionHistoryResponse(
    string Source,
    string Status,
    string HistoryRootPath,
    int TotalExecutions,
    IReadOnlyList<RuntimeStackBackupPublicCutoverExecutionSummary> Executions,
    IReadOnlyList<string> Warnings,
    string? Detail);

public sealed record RuntimeStackBackupPublicCutoverExecutionDetailResponse(
    string Source,
    string Status,
    string HistoryRootPath,
    RuntimeStackBackupPublicCutoverExecutionResult? Execution,
    IReadOnlyList<string> Warnings,
    string? Detail);

public sealed record RuntimeStackBackupPublicCutoverExecutionSummary(
    string ExecutionId,
    string ConfirmationId,
    string PreviewId,
    string ValidationId,
    string CandidateId,
    string? FreshPlanId,
    string RestoreMode,
    string Status,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset? FinishedAtUtc,
    string? Operator,
    bool NpmRouteExecutionPerformed,
    bool CutoverIngressNetworkExecutionPerformed,
    bool RuntimePromotionLocked,
    bool DnsMutationLocked,
    bool CertificateMutationLocked,
    bool MatrixSucceeded,
    bool ElementSucceeded,
    bool AnyRouteMutated,
    bool CutoverIngressReady,
    bool DockerNetworksChanged,
    int BlockerCount,
    int WarningCount,
    int ErrorCount,
    string? Detail);
